--- #YAML:1.0
name: Bot-BasicBot-Pluggable-Module-Weather
version: 0.9
author: Simon Wistow <simon@thegestalt.org>
abstract: |-
  various Weather and Aviation plugins for Bot::BasicBot::Pluggable
license: perl
requires:
  Bot::BasicBot::Pluggable: 0.5
  Geo::WeatherNWS: 0
  HTML::Entities: 0
  LWP::Simple: 0
  Test::More: 0
provides:
  Bot::BasicBot::Pluggable::Module::Aviation:
    file: lib/Bot/BasicBot/Pluggable/Module/Aviation.pm
  Bot::BasicBot::Pluggable::Module::Weather:
    file: lib/Bot/BasicBot/Pluggable/Module/Weather.pm
generated_by: Module::Build version 0.25
